sudo: false
language: python
python:
- '2.7'
- '3.5'
install:
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
- pip install -e .
- pip list
script:
- mamba
- pip list
deploy:
  provider: pypi
  user: xtorello
  password:
    secure: KMb9DcbuT4vpa0ptjKsX6f548X/RoXJfl+UVYfXN39KAVu0dVMGlaR6p2bIgnvuA44vBCxZ+7RfEpvtqQokxqhJPvYhSSvscxhcHpwhSDEkbppCHhAntI+nxSwTjgS3m4UKp1EtENSmuHmJErxWkebIClzthsR/WZ+/SpqzmVxlVZ8IebzLOXq6ktQInDkJR6ciPYcFOs7rdFnz+J6qW3TaoSrSOV/jZn8ySjx1PD3s9GWFFyeB55WjYabFUGlK35vaHwWvvn6BKR/f/L4tG54XoG2QKIBtjPonxFv80V3Vgg5rXTuC+wL4L7uQDXQgBLI2Xc/00utg0GJvlDLSqXU4+V8V6IDb7Yz/OUsk7n33hikT8M30GwpgQ6jAKgSQY3o9yrrj9TBrRRgEjGfG1MhQAZhy/BJrkOebSsFWRzO/03TotdwIorLtCPz0/JSMwlXQ4zQ2dKku8w2P5nq6HphCZHU4lCnRG/uEJ4cCZktaVPcaoa69Ab6HLjXA+Mop31df0yiH/dj2/yZFZ0iwKf3tAkKMC+18UYAOFiQ+9UWROSoEPiOOBmsbKVWIJz2R5OcZDqWDzxIl/XQMPRcHmLuIaWXjbChm1+o5/dWdoMBj4n6xXRYnxqr7lIQf3afdUrxoRQLWDHj2wlJst7q8YOMTqq4isECg/rsNdmm0HpOI=
  on:
    branch: master
