sudo: false
language: python
python:
- '2.7'
- '3.5'
install:
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
- pip install -e .
- pip list
script:
- mamba
- pip list
deploy:
  provider: pypi
  user: xtorello
  password:
    secure: AJpBhn3hmi+rWWG6i7HANoxC6Z9t1iuomlwTnojyEPr/4b2gZ60FLg+e8ttlNfKXnjoOip8VBHXfIl8+r2hX3JarSUSlek7qPSKKNUH1iROlesY7BP8jjto4SyszDoZNYapCcMlz+tPTCMfOIMrNCy/7CgNsHNbhcdMkGDoBuHbnRprjcOTzhaU+wBrPJ9JlH7S/vdieaLN4DiwWYw3LLwwVvuadRIfZThRbZuueQ0OMO8RfO/EdsUMcfOCNdjMfW6X9LVRMo8SIkc+G8BrVsGUBF/xPeBA53BsOeT/0b4GGKuZlsblxqdePQAdLJufp2CjFItbqaEb82mn/GUDNFgWclNinhgIGszo+1HLE5H7tro+PAW7k9TX7XlmAL/3uJzw7vsB86UTeiKtu83GphXSGj67XumeOrv6G+CEq4XoVsLcA26isOFJDtYxjpk3F83GC6vDHRof8sFsjxr84l6ONZZlvTD6Z03VpjaX4r4jO0i1FhkXOvTRivLY7gd0GTW3rCPBOKtmIetPBCNP+WyySN/9a1BZB7kEb0MsibYdMdjlBEfbuiTpjZoimG+Mbg3gRcjGOJXV39NEPxQi47MFHqK74FW1pv7CkuT3Tga5TSB2BkD+l7qLeK/aYa6WZlno1PTtlBjlOqkfI3Sy53S0t/4Of0DVTMNq4AAC1bbI=
  on:
    branch: master
